# Generated by Django 3.0.7 on 2020-11-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201111_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='quote',
            field=models.CharField(default='isn', max_length=512),
            preserve_default=False,
        ),
    ]
