# Generated by Django 3.0.7 on 2020-10-26 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comments'),
        ('blog', '0002_auto_20181020_1800'),
    ]

    operations = [
    ]
