# Generated by Django 3.0.7 on 2020-11-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201103_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='no',
        ),
    ]
