# Generated by Django 3.0.7 on 2020-11-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_comments_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/comment'),
        ),
    ]
