from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCategory,
    PostCreateView,
    PostUpdateView,
    UpdateComment,
    PostDeleteView,
    CommentDeleteView,
    UserPostListView,
    FollowsListView,
    test,
    ProfileListView,
    FollowersListView,
    ve,
    post_single,
    post_create,
    postpreference,
    commentpreference,)

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post_new/', post_create, name='create'),
    #path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/<int:pk>/<slug:slug>/', post_single, name='post_single'),
    path('test/', test, name='test'),
    path('post/category/<str:category>', PostCategory.as_view(), name='post-category'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('comment/<int:pk>/edit/', UpdateComment.as_view(), name='comment-update'),
    path('post/<int:pk>/del/<str:post/', PostDeleteView.as_view(), name='post-delete'),
    path('comment/<int:pk>/del/<str:post/', CommentDeleteView.as_view(), name='comment-delete'),
    path('user/<str:username>/follows', FollowsListView.as_view(), name='user-follows'),
    path('user/<str:username>/followers', FollowersListView.as_view(), name='user-followers'),
    path('user/<str:username>', ProfileListView.as_view(), name='user'),
    path('post/<int:postid>/<int:userpreference>', postpreference, name='postpreference'),
    path('comment/<int:postid>/<int:userpreference>', commentpreference, name='commentpreference'),
    path('v/', ve, name='vend'),
]