# Generated by Django 3.0.7 on 2020-10-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0003_auto_20200428_0620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['timestamp']},
        ),
    ]
