# Generated by Django 3.0.7 on 2020-11-14 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0004_auto_20201002_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeluser',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
