# Generated by Django 3.0.7 on 2020-11-14 23:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0005_channeluser_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmessage',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
